config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  root to: 'home#index'
  
  # devise_for :users
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  resources :workouts,    only: %i[index edit create stop resume destroy] do
    collection do
      get '/',            to: 'workouts#index'
      get 'start',        to: 'workouts#start'
      get 'stop',         to: 'workouts#stop'
      get 'resume',       to: 'workouts#resume'
    end
  end
  
  resources :setts,         only: %i[update]
  resources :routines,      only: %i[index]
  resources :exercises,     only: %i[index]
  resources :templates,     only: %i[index]
  resources :charts,        only: %i[index]
  resources :settings,      only: %i[index update]
  resources :achievements,  only: %i[index]
  resources :settings,      only: %i[index]
  resources :timeline,      only: %i[index]
  resources :relationships, only: %i[create ]

  resources :relationships, only: %i[create] do
    collection do
      post 'unfollow',           to: 'relationships#unfollow'
      post 'approve',            to: 'relationships#approve'
      post 'reject',             to: 'relationships#reject'
      post 'cancel_request',     to: 'relationships#cancel_request'
      post 'remove_invitation',  to: 'relationships#remove_invitation'
    end
  end
  
  resources :api,           :defaults => {:format => :json} do
    collection do
      get 'charts',         to: 'api#charts'
      get 'workouts',       to: 'api#workouts'
    end
  end


  resources :tutorials,      only: %i[index]
  get "/tutorials/:exercise/:page",   to: "tutorials#show"



  
  get '/billing' => 'billing#index', as: :billing
  get '/card/new' => 'billing#new_card', as: :add_payment_method
  get '/success' => 'billing#success', as: :success
  post '/card' => 'billing#create_card', as: :create_payment_method  
  
    
end

app/models/user/workouts.rb
module User::Workouts
  extend ActiveSupport::Concern


  def start_workout
    CreateUserWorkout.new(self).call
  end
    
  
  def end_workout(workout)
    CompleteUserWorkout.new(self).call(workout)
  end
  
  
  def active_workout
    self.workouts.where("active = true").first
  end
  
  
  def has_active_workout?
    active_workout ? true : false
  end

  # previous_workout is looking for the previous before the current one.
  def previous_workout
    Workout.where(user_id: self.id).last(2).first
  end
  
  # most recent workout and previous might seem similar but it's important not to confuse them
  # most_recent_work gets the most recent workout, whether there is an active one or not
  def most_recent_workout
    Workout.where(user_id: self.id).last
  end


  def chart_user_workouts
    CreateUserWorkoutChart.new(self).call
  end
  
  
  # TODO: stale?
  def workout_exercise_was_succcessful(workout_id, exercise_id)
    successful_sets = Workout.find(workout_id).setts.where(exercise_id: exercise_id).map{|e|
      (e.reps_completed == e.reps_goal) && (e.reps_completed > 0)
    }
    self.where(exercise_id: exercise_id).exists? && successful_sets.all? {|a|a}
  end
  
  
  def next_workout_date
    # this is not pretty, but I needed to get this out quickly to test other things
    # TODO: rewrite to take multiple algorithms for different programs. this is currently 5x5
    # Routine.find(self.routine_id).templates.where(exercise_id: exercise_id, exercise_group: exercise_group).first.incremention_scheme.fetch(set_number).to_i
    week_array = [false,true,false,true,false,true,false] # this is basically 5x5/M-W-F
    wday = Time.now.wday

    week_array.each_with_index do |value, key|
      wnext = (wday + key)%week_array.count
      if week_array.fetch(wnext)
        return Time.now + key.days
      end
    end
    
    # We should never be here.
    Rails.logger.error {"User.next_workout_date not finding the next workout date and defaulting to tomorrow"}
    Time.now + 1.days
  end


  def personal_records
    
    response = []
    if self.routine
      response = self.routine.distinct_exercises.map {|exercise|
        self.highest_weight_sett(exercise.id).try("id")
      }
    end
    
    response.any? ? Sett.find(response) : []
    
  end


  def personal_achivements
    []
  end



  def highest_weight_sett(exercise_id)
    Sett.where(user_id: self.id, exercise_id: exercise_id).where("reps_completed > 0").order(weight: :desc).limit(1).first || Sett.none
  end

end

app/models/workout.rb
#------------------------------------------------------------------------------
# Workout
#
# Name           SQL Type             Null    Primary Default
# -------------- -------------------- ------- ------- ----------
# id             bigint               false   true              
# user_id        integer              false   false             
# routine_id     integer              false   false             
# active         boolean              false   false   false     
# exercise_group character varying    false   false             
# notes          text                 true    false             
# created_at     timestamp without time zone false   false             
# updated_at     timestamp without time zone false   false             
# completed_at   timestamp without time zone true    false             
# results        jsonb                true    false             
# began_at       timestamp without time zone true    false             
#
#------------------------------------------------------------------------------

class Workout < ApplicationRecord
  belongs_to :routine
  has_many :setts
  has_many :exercises, through: :setts

  belongs_to :user, required: false


  def distinct_exercises
    Exercise.find( self.setts.select(:exercise_id).distinct.map{|e|e.exercise_id} )
  end


  def current_exercise_weight(exercise_id)
    # self.previous_exercise_setts(exercise_id).max_by(&:weight).try(:weight).to_i
    self.setts.where("exercise_id = :exercise_id", { exercise_id: exercise_id }).max_by(&:weight).try(:weight).to_i
  end
  
  def formated_date
    self.began_at.strftime("%A, %b %d %Y")
  end
  
  def current_results(exercise_id)
    self.results.find{|e|e["exercise_id"] == exercise_id}.to_h["weight"]    
  end
  
  
  # Useful to clearing all the default values with new structure.
  def self.regenerate_all_workout_results
    Workout.all.each do |workout|
      CompleteUserWorkout.new(User.find(workout.user_id)).call(workout)
    end
  end
  
  # Spaces out all the workouts by one day. Useful for testing lots of data.
  def self.space_workout_dates    
    length = Workout.all.count
    Workout.all.each do |workout|
      workout.began_at = length.days.ago
      workout.save!
      length = length - 1
    end
  end
  

end

app/controllers/workouts_controller.rb
# frozen_string_literal: true

class WorkoutsController < ApplicationController
  # helper_method :filtering_params

  def index
    paginate = 100
    
    offset = profile_params[:page].to_i * paginate
    
    @workouts = current_user.workouts.order(began_at: :desc).offset(offset).limit(paginate)
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @workouts.as_json  }
    end
  end

  def show
    @workout = Workout.where(id: params[:id], user_id: current_user.id).first
  end

  def edit
    @workout = Workout.where(id: params[:id], user_id: current_user.id).first
  end

  def start
    if current_user.routine_id > 0
    
      @workout = current_user.active_workout || current_user.start_workout
      fresh_when(@workout)
      unless @workout
        flash[:alert] = 'Cannot create a new task'
      end
      redirect_to edit_workout_path(@workout)
      
    else
      flash[:alert] = 'Please select a routine'
      redirect_to routines_path
    end
    
  end

  def resume
    if current_user.active_workout
      redirect_to edit_workout_path(current_user.active_workout.id) #"/workouts/#{current_user.active_workout.id}/edit"
    else
      redirect_to workouts_path #"/#{current_user.username}/workouts"
    end
  end

  
  def stop
    workout = current_user.active_workout
    current_user.end_workout(workout)
    cookies.delete :restTime
    redirect_to workouts_path 
  end

  
  def update
    Rails.logger.info{ workout_params[:title] }
    if Workout.find(params[:id]).update(workout_params.to_h)
      head :ok
    else
      flash[:alert] = 'Workout title cannot be blank'
    end
  end
  


  def destroy
    @workout = Workout.where(id: params[:id], user_id: current_user.id).first
    
    if @workout.destroy
      head :ok
    else
      flash[:alert] = 'Cannot delete workout'
    end
  end
  

  private

    def workout_params
      params.require(:workout).permit(:id, :title, :completed, :completed_filter)
    end


    def profile_params
      params.permit(:page)    
    end


end

app/helpers/workouts_helper.rb
module WorkoutsHelper
  
  

end

app/views/workouts/_empty.haml
.empty
  .empty-icon
    %i.icon.icon-3x.icon-mail
  %p.empty-title.h5 You have no workouts 
  %p.empty-subtitle hello
  .empty-action
    =link_to "/workouts/create" do
      %button.btn.btn-primary Begin new workout

app/views/workouts/_notification.haml
#notification{class: "#{'notification-active' if workout.active }" }
  .content
    =render "rest_timer", cached: true
    

app/views/workouts/_rest_timer.haml
#restTimer.timer-container{"data-controller" => "rest-timer"}
  %input#restTime{type: "hidden", value: current_user.settings('rest_time').to_i + 1}
  .controlls
    %span.display-remain-time{"data-target" => "rest-timer.view"} 00:00
  Rest between rests

app/views/workouts/_workout.haml
= cache workout do
  %h3{style: "text-align: center"}
    -if workout.active == true
      Active Workout
    -else
      Previous Workout
    
  =render "notification", workout: workout
  %input{ type: 'hidden', id: "active_workout", value: workout.active.to_s }
  .panel.card{ class: ("inactive" if workout.active === false) }
    .card-header
      .card-title.h5.column
        .columns
          .col-12
            =link_to workout.formated_date, edit_workout_path(workout)
      =render "workout_timer", workout: workout

      .card-subtitle.text-gray
      .card-body.columns
        - workout.distinct_exercises.each do |exercise|
          .columns{style: "border-bottom: 2px solid white"}
            %h5
              -if workout.active === false 
                %span.circle{class: "#{workout.results.find{|e|e.to_h["exercise_id"] == exercise.id}.to_h["success"] ? 'green' : 'red'}"}            
              = exercise.name
              /
              / Training Max
              / %input{type: "number", min: 0, max: 2000, step: 2.5, value: sett.weight, "data-target" => "sett.weight", "data-action" => "change->sett#updateWeight"}

          / .columns.col-12
          /   Training Max:
          /   =workout.current_results(exercise.id)
          .column.col-12{style: "font-size: 15pt"}
            - workout.setts.where(exercise_id: exercise.id).order(:id).each_with_index do |sett, index|
              .columns.col-12{"data-controller" => "sett", "data-sett-id" => sett.id, "data-sett-active" => "#{workout.active.to_s}", "data-sett-completed-at" => workout.completed_at}
                .col-1.left
                  %small
                    ="#{index+1}.  "
                .col-5

                  %span
                    / -if workout.active
                    /   %input{style: "width: 75px; text-align: center", type: "number", min: 0, max: 2000, step: 2.5, value: sett.weight, "data-target" => "sett.weight", "data-action" => "change->sett#updateWeight"}
                    
                    ="#{sett.weight}"
                    %span lbs
                    
                    / -if workout.active
                    /   %input{style: "width: 75px; text-align: center", type: "number", min: 0, max: 2000, step: 2.5, value: sett.weight, "data-target" => "sett.weight", "data-action" => "change->sett#updateWeight"}

                
                / #gUMArea
                /   %div
                /     Record:
                /     = succeed "Video" do
                /       %input#mediaVideo{:checked => "checked", :name => "media", :type => "radio", :value => "video"}/
                /     = succeed "audio" do
                /       %input{:name => "media", :type => "radio", :value => "audio"}/
                /   %button#gUMbtn.btn.btn-default Request Stream
                / #btns
                /   %button#start.btn.btn-default Start
                /   %button#stop.btn.btn-default Stop
                / %div
                /   %ul#ul.list-unstyled

                .col-1{"data-controller" => "video"}
                  -if ENV['FEATURE_VIDEO']
                    .btn-sm
                      %img.icon-video{src: "#{asset_pack_path('images/video.png')}", "data-target" => "video.button", "data-value" => "0", "data-action" => "click->video#toggleVideoRecord"}
                  
                .right.col-5
                  %button.btn.btn{"data-target" => "sett.button", "data-action" => "click->sett#updateReps", :class => ("btn-primary-light-red" if sett.reps_completed < sett.reps_goal)}
                    .div{"data-target" => "sett.reps", "value" => "0"}
                      ="#{sett.reps_completed} x #{sett.reps_goal}"
                    
              

      .panel-footer.card-footer
        -if workout.active
          %span.complete-workout.col-12.btn
            %a{href: '/workouts/stop'}
              Finish

      .panel-footer
        -#=f.submit "Save", :class => 'btn btn-primary btn-block', "data-target" => "form.submit", "data-action" => "click->form#onSubmit"

app/views/workouts/_workout_timer.haml
%span Total Time:
%span#workoutTimer{"data-controller" => "workout-timer", "data-target" => "workout-timer.view", "data-workout-timer-began-at" => "#{workout.began_at.to_i}", "data-workout-timer-completed-at" => "#{workout.completed_at.to_i}"}

app/views/workouts/edit.haml
= cache @workout do
  = render @workout, cached: true

app/views/workouts/index.haml
/ -if !current_user.has_active_workout?
/   .card
/     .card-body.columns
/       .column.col-12
/         .col-12
/           Your next workout is scheduled for
/           %b="#{formated_date(current_user.next_workout_date)}"
/       .column
/         .column
/           .columns
/             %a.col-12.btn{:href => start_workouts_path}  New Workout
/
/
        
  
-first_workout = Workout.order(began_at: :asc).limit(1).first.began_at.to_date
-week_number = first_workout.upto(first_workout + 1.week).count.fdiv(7).round(0) + 1
-show_week = {}
-@workouts.each do |workout|
  -if workout.active == true
    %h3{style: 'margin-top: 0'}
      Today
  -if workout.active == false 
    -current_workout = workout.began_at.to_date.beginning_of_week
    -number = first_workout.upto(current_workout).count.fdiv(7).round(0) + 1    
    -unless show_week.to_h[number]
      %h3{style: 'margin-top: 0'}
        =" Week ##{number}"
        -show_week[number] = true

  .card{id: "workout-#{workout.id}", "data-controller" => "card", class: ("inactive" if workout.active == false)   }
    =link_to edit_workout_path(workout) do 
      .card-header
        .card-subtitle
          =workout.formated_date 
          
        .card-body.columns
          - workout.distinct_exercises.each do |exercise|
            .col-7
              -if workout.active === false 
                %span.circle{class: "#{workout.results.find{|e|e.to_h["exercise_id"] == exercise.id}.to_h["success"] ? 'green' : 'red'}"}
              =exercise.name
            .col-3
              ="#{workout.current_exercise_weight(exercise.id)} lbs"
            .col-2
              =workout.routine.try(:name)
  
    =link_to workout_path(workout), method: :delete, remote: :true, data: { "card-workout-id" => workout.id, confirm: 'Are you sure?',  action: 'ajax:beforeSend->card#onBeforeDestroy ajax:success->card#onDestroy' }  do 
      .icon-trash 
        -#{"data-action" => "click->card#destroy", "data-card-workout-id" => workout.id}
        .trash-lid{:style => "background-color: #ff5964"}
        .trash-container{:style => "background-color: #ff5964"}
        .trash-line-1
        .trash-line-2
        .trash-line-3


-if @workouts.count > 100
  .column
    .column
      .columns
        %a.col-12.btn{style: "color: white", href: start_workouts_path}  Load More

app/views/workouts/show.haml
%table.table.table-striped.table-hover{"data-controller" => "workout-list"}
  %thead
    %tr
      %th name
      %th date
  %tbody.workoutapp
    = cache @workouts do
      %tr.workout-list
        = render @workouts, cached: false