config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  root to: 'home#index'
  
  # devise_for :users
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  resources :workouts,    only: %i[index edit create stop resume destroy] do
    collection do
      get '/',            to: 'workouts#index'
      get 'start',        to: 'workouts#start'
      get 'stop',         to: 'workouts#stop'
      get 'resume',       to: 'workouts#resume'
    end
  end
  
  resources :setts,         only: %i[update]
  resources :routines,      only: %i[index]
  resources :exercises,     only: %i[index]
  resources :templates,     only: %i[index]
  resources :charts,        only: %i[index]
  resources :settings,      only: %i[index update]
  resources :achievements,  only: %i[index]
  resources :settings,      only: %i[index]
  resources :timeline,      only: %i[index]
  resources :relationships, only: %i[create ]

  resources :relationships, only: %i[create] do
    collection do
      post 'unfollow',           to: 'relationships#unfollow'
      post 'approve',            to: 'relationships#approve'
      post 'reject',             to: 'relationships#reject'
      post 'cancel_request',     to: 'relationships#cancel_request'
      post 'remove_invitation',  to: 'relationships#remove_invitation'
    end
  end
  
  resources :api,           :defaults => {:format => :json} do
    collection do
      get 'charts',         to: 'api#charts'
      get 'workouts',       to: 'api#workouts'
    end
  end


  resources :tutorials,      only: %i[index]
  get "/tutorials/:exercise/:page",   to: "tutorials#show"



  
  get '/billing' => 'billing#index', as: :billing
  get '/card/new' => 'billing#new_card', as: :add_payment_method
  get '/success' => 'billing#success', as: :success
  post '/card' => 'billing#create_card', as: :create_payment_method  
  
    
end

app/views/templates/_form.html.haml
= form_for @template do |f|
  - if @template.errors.any?
    #error_explanation
      %h2= "#{pluralize(@template.errors.count, "error")} prohibited this exercise from being saved:"
      %ul
        - @template.errors.full_messages.each do |message|
          %li= message
      

  .columns.col-12.field.form-group

    .col-12
      = f.label :routine_id
      = f.hidden_field :routine_id,  :value => @template.routine_id
  
    .col-12
      - if @exercises && @exercises.any?
        =f.collection_select(:exercise_id, @exercises, :id, :name)
      - else
        %p No exercises available
        = link_to 'New Exercise', new_exercise_path
    
    .col-12
      = f.label :sets
      %br/
      = f.text_field :sets

    .col-12
      = f.label :reps
      %br/
      = f.text_field :reps

    .col-12
      = f.label :group
      %br/
      = f.text_field :group

    .col-12
      = f.label :progression_type
      %br/
      = f.text_field :progression_type


  .actions
    = f.submit 'Save'

app/views/templates/edit.html.haml
%h1 Editing template

= render 'form'

= link_to 'Show', @template
\|
= link_to 'Back', templates_path

app/views/templates/index.html.haml
/ This list page should only appear for admin
%h1 Listing templates

%table
  %thead
    %tr
      %th
      %th
      %th

  %tbody
    - @templates.each do |template|
      %tr
        %td= link_to 'Show', template
        %td= link_to 'Edit', edit_template_path(template)
        %td= link_to 'Destroy', template, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Template', new_template_path

app/views/templates/new.html.haml
%h1 New template

= render 'form'

= link_to 'Back', templates_path

app/views/templates/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_template_path(@template)
\|
= link_to 'Back', templates_path