config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  root to: 'home#index'
  
  # devise_for :users
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  resources :workouts,    only: %i[index edit create stop resume destroy] do
    collection do
      get '/',            to: 'workouts#index'
      get 'start',        to: 'workouts#start'
      get 'stop',         to: 'workouts#stop'
      get 'resume',       to: 'workouts#resume'
    end
  end
  
  resources :setts,         only: %i[update]
  resources :routines,      only: %i[index]
  resources :exercises,     only: %i[index]
  resources :templates,     only: %i[index]
  resources :charts,        only: %i[index]
  resources :settings,      only: %i[index update]
  resources :achievements,  only: %i[index]
  resources :settings,      only: %i[index]
  resources :timeline,      only: %i[index]
  resources :relationships, only: %i[create ]

  resources :relationships, only: %i[create] do
    collection do
      post 'unfollow',           to: 'relationships#unfollow'
      post 'approve',            to: 'relationships#approve'
      post 'reject',             to: 'relationships#reject'
      post 'cancel_request',     to: 'relationships#cancel_request'
      post 'remove_invitation',  to: 'relationships#remove_invitation'
    end
  end
  
  resources :api,           :defaults => {:format => :json} do
    collection do
      get 'charts',         to: 'api#charts'
      get 'workouts',       to: 'api#workouts'
    end
  end


  resources :tutorials,      only: %i[index]
  get "/tutorials/:exercise/:page",   to: "tutorials#show"



  
  get '/billing' => 'billing#index', as: :billing
  get '/card/new' => 'billing#new_card', as: :add_payment_method
  get '/success' => 'billing#success', as: :success
  post '/card' => 'billing#create_card', as: :create_payment_method  
  
    
end

app/models/user/settings.rb
module User::Settings
  
  extend ActiveSupport::Concern  
  
  def bar_weight
    # this should be stored in a setting somewhere
    return 45
  end
  
  def settings(keyname)
    
    default = {}
    default["rest_time"] = (60*3) # minutes
    default["bar_weight"] = 45
    
    return self.details.to_h[keyname] if self.details.to_h[keyname]
    return default.to_h[keyname] if default.to_h[keyname]
    return nil
  end
  
  
  
  def generate_milestones
    
    timeline = {}
    
  end
  
  
  def set_default_user_settings
    self.routine = Routine.first
    self.details = {"body_weight"=>"", "equipment_bar"=>"45", "equipment_type"=>"barbell", "equipment_plates"=>"45"}
    self.save!
  end
  

  
  
end

app/controllers/settings_controller.rb
require 'digest'


class SettingsController < ApplicationController

  def index
    @user = current_user
    @user_email_hash = Digest::MD5.hexdigest(current_user.email)
    unless current_user
      render :file => "#{Rails.root}/public/404.html",  layout: false, status: :not_found
    end
  end
  
  def update
    # byebug
    current_user.update!(user_detail_params)    
  end
  
  def premium_subcription

  end
  

  private
    

  def user_detail_params
    
    params.require(:user).permit(:email, 
      details:[
        :equipment_type, 
        :equipment_plates, 
        :equipment_bar, 
        :body_weight
      ])
  end



end

app/views/settings/goals.haml
.panel
  .panel-header.text-center
  .panel-body
    .calendar
      / calendar navbar
      .calendar-nav.navbar
        %button.btn.btn-action.btn-link.btn-lg
          %i.icon.icon-arrow-left
        .navbar-primary March 2017
        %button.btn.btn-action.btn-link.btn-lg
          %i.icon.icon-arrow-right
      .calendar-container
        .calendar-header
          .calendar-date Sun
          .calendar-date Mon
          .calendar-date Tue
          .calendar-date Wed
          .calendar-date Thu
          .calendar-date Fri
          .calendar-date Sat
        .calendar-body
          / calendar previous month
          .calendar-date.prev-month
            %button.date-item 26
          \...
          .calendar-date.prev-month
            %button.date-item 28
          / calendar current month
          .calendar-date
            %button.date-item 1
          .calendar-date
            %button.date-item 2
          .calendar-date
            %button.date-item 3
          / calendar date: today
          .calendar-date
            %button.date-item.date-today 4
          / calendar date: tooltip
          .calendar-date.tooltip{"data-tooltip" => "You have appointments"}
            %button.date-item 5
          / calendar date: not available
          .calendar-date.tooltip{"data-tooltip" => "Not available"}
            %button.date-item{:disabled => "disabled"} 6
          / calendar range
          .calendar-date.calendar-range.range-start
            %button.date-item 7
          .calendar-date.calendar-range
            %button.date-item 8
          .calendar-date.calendar-range.range-end
            %button.date-item 9
          \...
          .calendar-date
            %button.date-item 31
          / calendar next month
          .calendar-date.next-month
            %button.date-item 1


  .panel-footer
    / %button.btn.btn-primary.btn-block Save

app/views/settings/index.haml
=form_with(model: @user, url: setting_path(@user)) do |f|
  .panel.card{"data-controller" => "form"}
    .panel-header.text-center
      / %figure.avatar.avatar-lg
      /   %img{:alt => "#{current_user.name}", :src => "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest current_user.email}"}/
      %figure.avatar.avatar-lg        
        =show_avatar(current_user.id)
        
      .panel-title.h5.mt-10=current_user.name
      .panel-subtitle=current_user.username
    .panel-body
      .tile.tile-centered
        .tile-content
          .tile-title.text-bold E-mail
          .tile-subtitle
            = f.text_field :email, value: current_user.email 

      .tile.tile-centered
        .tile-content
          .tile-title.text-bold Workout Program
          .tile-subtitle=current_user.routine.name


      = f.fields_for :details, OpenStruct.new(@user.details) do |ff|
        / .tile.tile-centered
        /   .tile-content
        /     .tile-title.text-bold Equipment Type
        /     .tile-subtitle
        /       = ff.text_field :equipment_type, value: current_user.settings("equipment_type")


        / .tile.tile-centered
        /   .tile-content
        /     .tile-title.text-bold Plates
        /     .tile-subtitle
        /       = ff.text_field :equipment_plates, value: current_user.settings("equipment_plates")
        /

        .tile.tile-centered
          .tile-content
            .tile-title.text-bold Bar Weight
            .tile-subtitle
              = ff.text_field :equipment_bar, value: current_user.settings("equipment_bar")

        / .tile.tile-centered
        /   .tile-content
        /     .tile-title.text-bold Body Weight
        /     .tile-subtitle
        /       = ff.text_field :body_weight, value: current_user.settings("body_weight")
            

        .tile.tile-centered
          .tile-content
            .tile-title.text-bold Disable Rest Timer
            .tile-subtitle
              = ff.check_box :disable_rest_timer, { multiple: false }, current_user.settings("disable_rest_timer"), current_user.settings("disable_rest_timer")
            

        .tile.tile-centered
          .tile-content
            .tile-title.text-bold Rest time between sets (in seconds)
            .tile-subtitle
              = ff.text_field :rest_time, value: current_user.settings("rest_time")
            


        .tile.tile-centered
          .tile-content
            = form_tag id: "billing-create-payment-method" do
              = link_to "Subscribe", add_payment_method_path, remote: true, class: "btn btn-primary"              
            

            



    .panel-footer
      =f.submit "Save", :class => 'btn btn-primary btn-block', "data-target" => "form.submit", "data-action" => "click->form#onSubmit"
      

app/views/settings/timeline.haml
.panel
  / .panel-header.text-center
  /   %figure.avatar.avatar-lg
  /     %img{:alt => "#{current_user.name}", :src => "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest current_user.email}"}/
  /   .panel-title.h5.mt-10
  /     =current_user.username
  /   .panel-subtitle=current_user.name
  .panel-body
    .timeline
      #timeline-example-1.timeline-item
        .timeline-left
          %a.timeline-icon.tooltip{"data-tooltip" => "March 2016", :href => "#timeline-example-1"}
        .timeline-content
          .tile
            .tile-content
              %p.tile-subtitle March 2016
              %p.tile-title Initial commit
      #timeline-example-2.timeline-item
        .timeline-left
          %a.timeline-icon.icon-lg.tooltip{"data-tooltip" => "February 2017", :href => "#timeline-example-2"}
            %i.icon.icon-check
        .timeline-content
          .tile
            .tile-content
              %p.tile-subtitle February 2017
              %p.tile-title New Documents experience
              %p.tile-title
                %a{:href => "components.html#bars"}> Bars
                \: represent the progress of a task
              %p.tile-title
                %a{:href => "components.html#steps"}> Steps
                \: progress indicators of a sequence of task steps
              %p.tile-title
                %a{:href => "components.html#tiles"}> Tiles
                \: repeatable or embeddable information blocks
            .tile-action
              %button.btn View
      #timeline-example-3.timeline-item
        .timeline-left
          %a.timeline-icon.icon-lg.tooltip{"data-tooltip" => "March 2017", :href => "#timeline-example-3"}
            %i.icon.icon-check
        .timeline-content
          .tile
            .tile-content
              %p.tile-subtitle March 2017
              %p.tile-title
                %a{:href => "elements.html#icons"}> Icons
                \: single-element, responsive and pure CSS icons
              %p.tile-title
                %a{:href => "components.html#popovers"}> Popovers
                \: small overlay content containers
              %p.tile-title
                %a{:href => "experimentals.html#calendars"}> Calendars
                \: date or date range picker and events display
              %p.tile-title
                %a{:href => "experimentals.html#carousels"}> Carousels
                \: slideshows for cycling images
            .tile-action
              %button.btn View

  .panel-footer
    / %button.btn.btn-primary.btn-block Save